- README.md
- force-app/main/default/classes/IBMConversationV1Models.cls
- force-app/main/default/classes/IBMDiscoveryV1.cls
- force-app/main/default/classes/IBMDiscoveryV1Models.cls
- force-app/main/default/classes/IBMWatsonDynamicModel.cls
- force-app/main/default/classes/IBMWatsonGenericModel.cls
- force-app/main/default/classes/IBMWatsonJSONUtil.cls
Fixes #9 
Dynamic properties located in the `additionalProperties` map are now exposed with the `@AuraEnabled` annotation, allowing access from Javascript.
Objects which may have additional properties will have an `additionalProperties` field, which can be treated like a normal object in Javascript. An example of getting the `text` property of the following response object is shown below:
`QueryResponse` JSON representation (simplified):
```
{
"matching_results": 2,
"results": [
{
"id": "my_id",
"score": 1.0,
"collection_id": "my_collection_id",
"additional_properties": {
"enriched_text": {
"concepts": [
{
"text": "my text"
}
]
}
}
},
// next result
]
}
```
Access using Javascript:
```javascript
action.setCallback(this, function(response) {
var resp = response.getReturnValue(); …
```
> Enable "additionalProperty" visibility through Javascript

- force-app/main/default/classes/IBMDiscoveryV1Models.cls
Fixes #65 
Some users were experiencing compilation errors due to a variable name in the `IBMDiscoveryV1Models` file. This PR makes the small fixes that were confirmed to solve the problem.
> Fix compilation error due to variable naming

- force-app/main/default/classes/IBMDiscoveryV1Models.cls
Some users reported an error with a variable name preventing successful compilation and therefore preventing them from being able to deploy the SDK using ant. This PR has a small fix to solve this issue.
> Fix compilation error preventing deployment

- README.md
I only see 4 instances of "Bluemix" in the README, so update it to "IBM Cloud" because that's the new name.
> change Bluemix to IBM Cloud

- force-app/main/default/classes/IBMWatsonJSONUtil.cls
- force-app/main/default/classes/IBMWatsonJSONUtilTest.cls
- force-app/main/default/classes/IBMWatsonService.cls
Fixes #70 
The `raiseAdditionalProperties()` method was incorrectly extracting just the additional properties at the top level of a JSON response. This PR fixes this issue by recursively calling the method on the specified JSON object.
A test has also been added to make sure this functionality doesn't break in the future.
I've also added back the util method to turn empty strings in the response strings into `null` values juuuuust in case.
> Fix handling of nested additional properties

- force-app/main/default/classes/IBMWatsonJSONUtil.cls
- force-app/main/default/classes/IBMWatsonService.cls
In my last PR to fix deserialization issues, I added back the utility method in `IBMWatsonJSONUtil` to replace empty JSON string values with `null`.
It turns out that addition shouldn't have been made, as I ran into issues parsing some calls due to that method. A particular example was trying to parse the response of a `listDialogNodes()` call with Discovery.
This PR removes that method and clears up that issue.
> Revert addition of JSON util method to replace empty string values

- force-app/main/default/classes/IBMWatsonDynamicModel.cls
- force-app/main/default/classes/IBMWatsonGenericModel.cls
The JSON serialization was removing newlines from the output. This caused issues when there were literal newlines in the JSON string and cause errors with HTML or XML content present in a JSON field value.
Would like to know why this included in the first place as it seems arbitrary to remove on the `toString`
Thanks for contributing to the Watson Developer Cloud!
> Remove the removal of newlines

- README.md
This PR removes references to the old static version date strings in documentation, since these have been removed in favor of explicitly specifying the desired version date in the latest release.
> Update references to old static version date strings

- force-app/main/default/classes/IBMNaturalLanguageClassifierV1.cls
- force-app/main/default/classes/IBMNaturalLanguageClassifierV1Models.cls
- force-app/main/default/classes/IBMNaturalLanguageClassifierV1Test.cls
- force-app/main/default/classes/IBMWatsonMockResponses.cls
- force-app/main/test/IBMNaturalLanguageClassifierV1FTests.cls
Recently, the NLC service added a new endpoint: `classifyCollection`. This PR adds that service method, as well as any associated models and accompanying tests.
> Add classifyCollection endpoint

- force-app/main/default/classes/IBMWatsonServiceTest.cls
This PR removes the use of the Discovery service from `IBMWatsonServiceTest`. This was problematic for users who just wished to deploy services other than Discovery, because the dependency was relying on Discovery being present as well.
> Remove Discovery dependency from core testing class

- .bumpversion.cfg
- .github/Contributing.md
- .releaserc
- RELEASES.md
Once again adding `semantic-release`. This should fully automate releases once code is merged into `master`.
> Add semantic-release integration

- force-app/main/default/classes/IBMWatsonMultipartBody.cls
Fixes #130 
This PR fixes a recurring issue the SDK has had uploading files. Testing for reproduction showed that files would upload successfully with certain filenames but not others (although any filename worked in my tests with `text/html` and `application/json` files).
The if-statement changed in this PR was identified as the only diverging point between uploading the above file types and something like `application/pdf`, which is the file type the bug was originally found with. After the change, I was able to successfully upload files of various types and names while retaining prior functionality.
> File upload fix

- force-app/main/default/classes/IBMWatsonService.cls
Fixes #129 and fixes #138 
This PR limits the SOQL query to build the user agent to just one record in the case that the SDK is deployed in multiple namespaces. This will fix errors for now, and it can be tweaked in the future if necessary.
> Limit SOQL call for user agent to one Apex class

- README.md
- force-app/main/default/classes/IBMWatsonService.cls
This PR adds deprecation warnings for the `X-Watson-Authorization-Token` header: once in the main README and once in the code. The method of warning in the code should behave identically to the proposed change in the Java SDK: https://github.com/watson-developer-cloud/java-sdk/pull/964
> Add CF token deprecation message

- force-app/main/default/classes/IBMWatsonService.cls
- force-app/main/default/classes/IBMWatsonServiceTest.cls
This PR handles the case where the user authenticates with a username and password in the following manner:
```
username: "apikey"
password: "<iam_apikey>"
```
The SDK now recognizes this and automatically creates an IAM token manager instance to handle it.
> Handle username and password authentication with "apikey"

- force-app/main/default/classes/IBMWatsonIAMTokenManager.cls
Removes the basic authentication header from the IAM token request because it is not necessary. If it is necessary, it needs to be stored in a secure way because currently it generated a security violation in the source code scanner when used in managed packages.
> Remove hardcoded basic auth from token manager

- README.md
This pull request removes the region specific `ng` from the iam url in the readme.
> docs(readme): remove ng from iam url

- force-app/main/default/classes/IBMWatsonService.cls
- force-app/main/default/classes/IBMWatsonServiceTest.cls
This PR ensures that users authenticating with an API key on ICP do not perform the usual token exchange, instead going through basic auth.
> Add support for ICP auth

- force-app/main/default/classes/IBMSpeechToTextV1.cls
- force-app/main/default/classes/IBMSpeechToTextV1Models.cls
This PR is a small patch to ensure that the `Content-Type` header in `createJob()` and `recognize()` are not required, since the service allows them not to be specified.
> Make content type optional in createJob() and recognize()

- force-app/main/default/classes/IBMAssistantV1Models.cls
- force-app/main/default/classes/IBMAssistantV2Models.cls
This PR has a fix each for Assistant v1 and v2.
For Assistant v1, a missing property has been manually added to the `CreateDialogNode` model. This will be automated soon (hopefully in the next release).
For Assistant v2, the `MessageOutput` model has been made dynamic to capture additional properties that aren't currently documented. These will be added properly in the next release as well.
> Fix issues with Assistant models

- force-app/main/default/classes/IBMWatsonCredentialUtils.cls
- force-app/main/default/classes/IBMWatsonCredentialUtilsTest.cls
- force-app/main/default/classes/IBMWatsonCredentialUtilsTest.cls-meta.xml
- force-app/main/default/classes/IBMWatsonIAMTokenManager.cls
- force-app/main/default/classes/IBMWatsonService.cls
This PR ensures that exceptions are thrown for credential values surrounded by `{}` or `""` characters. This prevents making a call to the service and provides a more helpful error message.
> Gracefully handle common errors in credential values

- force-app/main/default/classes/IBMAssistantV1.cls
- force-app/main/default/classes/IBMAssistantV1Models.cls
This PR fixes the _attempted_ fix in https://github.com/watson-developer-cloud/salesforce-sdk/pull/167 by moving the missing `disabled` property from the `CreateDialogNode` model to the `DialogNode` model.
Any other changes are just documentation-related.
> Add missing property in Assistant v1 to correct model

- README.md
- force-app/main/default/classes/IBMAssistantV1.cls
- force-app/main/default/classes/IBMAssistantV2.cls
- force-app/main/default/classes/IBMCompareComplyV1.cls
- force-app/main/default/classes/IBMDiscoveryV1.cls
- force-app/main/default/classes/IBMLanguageTranslatorV3.cls
- force-app/main/default/classes/IBMNaturalLanguageClassifierV1.cls
- force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1.cls
- force-app/main/default/classes/IBMPersonalityInsightsV3.cls
- force-app/main/default/classes/IBMSpeechToTextV1.cls
- force-app/main/default/classes/IBMTextToSpeechV1.cls
- force-app/main/default/classes/IBMToneAnalyzerV3.cls
- force-app/main/default/classes/IBMVisualRecognitionV3.cls
- force-app/main/default/classes/IBMWatsonCredentialUtils.cls
- force-app/main/default/classes/IBMWatsonCredentialUtilsTest.cls
- force-app/main/default/classes/IBMWatsonService.cls
- force-app/main/default/classes/IBMWatsonServiceTest.cls
This PR adds support for a credential file downloaded from IBM Cloud. Due to restrictions of the Salesforce platform, the file will only be searched for in the **Static Resources** section of the user's Salesforce dashboard. The resource must be named `ibm_credentials*. Documentation has been added to the README to explain these steps.
Otherwise, this functionality behaves in the same way as the other SDKs.
> Support credential file

- force-app/main/default/classes/IBMAssistantV1.cls
- force-app/main/default/classes/IBMAssistantV2.cls
- force-app/main/default/classes/IBMCompareComplyV1.cls
- force-app/main/default/classes/IBMDiscoveryV1.cls
- force-app/main/default/classes/IBMLanguageTranslatorV3.cls
- force-app/main/default/classes/IBMNaturalLanguageClassifierV1.cls
- force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1.cls
- force-app/main/default/classes/IBMPersonalityInsightsV3.cls
- force-app/main/default/classes/IBMSpeechToTextV1.cls
- force-app/main/default/classes/IBMTextToSpeechV1.cls
- force-app/main/default/classes/IBMToneAnalyzerV3.cls
- force-app/main/default/classes/IBMVisualRecognitionV3.cls
- force-app/main/default/classes/IBMWatsonService.cls
This PR adds a header for each method call which sends analytics information about the service, version, and endpoint called. It also tweaks the format of the `User-Agent` header to match that of the other SDKs for the most part. Here's an example of the new `User-Agent`:
`watson-apis-salesforce-sdk-3.2.1 41.0`
The last value after the SDK version is the Apex API version. There's no OS information since it runs on the Salesforce cloud.
> Add headers for analytics

- .bumpversion.cfg
- .releaserc
- .travis.yml
- force-app/main/default/classes/IBMWatsonService.cls
Something seems to have gotten messed up with the automated release process and the last one failed. The fix in this PR has been used in the Swift and .NET SDKs with success so hopefully it works here too.
> Attempt to fix automated releases

- force-app/main/default/classes/IBMWatsonCredentialUtils.cls
- force-app/main/default/classes/IBMWatsonCredentialUtilsTest.cls
- force-app/main/default/classes/IBMWatsonIAMTokenManager.cls
Related to an internal naming debate. Basically, we've decided we should be using `iam_apikey` for IAM keys and are updating code on the IBM Cloud side to adhere to this. This will then require updating on the SDK side to capture those changes.
In this PR, we still do look for the old `apikey` name so as not to break anyone who may have been using an old credential file.
Lastly, I also included a change to try and pull the error message from bad IAM responses, which use the key `errorMessage`. This is a small change just to try and make those problems more readable.
> Look for iam_apikey for IAM auth in credential file

- .bumpversion.cfg
- .releaserc
- .travis.yml
- force-app/main/default/classes/IBMWatsonService.cls
This PR will _hopefully_ fix the issue we're currently having with the version numbers not getting updated on `master`. I've tried to match the configuration used in the [.NET SDK core](https://github.com/IBM/dotnet-sdk-core) which seems to be working well.
> Semantic release fix

- force-app/main/default/classes/IBMWatsonIAMTokenManager.cls
This PR fixes an issue where we were trying to use an `Object` as a `String` while doing error handling in the `IBMWatsonIAMTokenManager` class.
> Fix illegal assignment from Object to String

- force-app/main/default/classes/IBMCompareComplyV1Models.cls
- force-app/main/default/classes/IBMCompareComplyV1Test.cls
- force-app/main/default/classes/IBMWatsonMockResponses.cls
This PR updates just the Compare and Comply service. It fixes two incorrect model definitions (`BodyCells` and `KeyValuePair`) while also adding the `ContractCurrencies` model.
> Update Compare and Comply to fix model definitions

- force-app/main/default/classes/IBMAssistantV1Test.cls
- force-app/main/default/classes/IBMAssistantV2Test.cls
- force-app/main/default/classes/IBMCompareComplyV1Test.cls
- force-app/main/default/classes/IBMDiscoveryV1Test.cls
- force-app/main/default/classes/IBMLanguageTranslatorV3Test.cls
- force-app/main/default/classes/IBMNaturalLanguageClassifierV1Test.cls
- force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Test.cls
- force-app/main/default/classes/IBMPersonalityInsightsV3Test.cls
- force-app/main/default/classes/IBMSpeechToTextV1Test.cls
- force-app/main/default/classes/IBMTextToSpeechV1Test.cls
- force-app/main/default/classes/IBMToneAnalyzerV3Test.cls
- force-app/main/default/classes/IBMVisualRecognitionV3Test.cls
Fixes #197 
Salesforce has a requirement that all code deployed to a user's organization must have a total code coverage of >= 75% to be deployed to production. This number had dipped in the SDK, and it was preventing the linked user from being able to deploy to production, specifically with Assistant and Natural Language Understanding.
This PR just goes through the test classes and bumps up the coverage. After the changes, I'm seeing **81%** coverage with the whole SDK deployed and **79%** coverage with Assistant v1, Assistant v2, Natural Language Understanding, and the core deployed.
> Raise code coverage over 75% threshold

- .travis.yml
- README.md
- force-app/main/default/classes/IBMAssistantV1.cls
- force-app/main/default/classes/IBMAssistantV1Models.cls
- force-app/main/default/classes/IBMAssistantV1Test.cls
- force-app/main/default/classes/IBMAssistantV2Models.cls
- force-app/main/default/classes/IBMAssistantV2Test.cls
- force-app/main/default/classes/IBMCompareComplyV1.cls
- force-app/main/default/classes/IBMCompareComplyV1Models.cls
- force-app/main/default/classes/IBMCompareComplyV1Test.cls
- force-app/main/default/classes/IBMDiscoveryV1.cls
- force-app/main/default/classes/IBMDiscoveryV1Models.cls
- force-app/main/default/classes/IBMDiscoveryV1Test.cls
- force-app/main/default/classes/IBMLanguageTranslatorV3.cls
- force-app/main/default/classes/IBMLanguageTranslatorV3Models.cls
- force-app/main/default/classes/IBMLanguageTranslatorV3Test.cls
- force-app/main/default/classes/IBMNaturalLanguageClassifierV1.cls
- force-app/main/default/classes/IBMNaturalLanguageClassifierV1Models.cls
- force-app/main/default/classes/IBMNaturalLanguageClassifierV1Test.cls
- force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Models.cls
- force-app/main/default/classes/IBMSpeechToTextV1.cls
- force-app/main/default/classes/IBMSpeechToTextV1Models.cls
- force-app/main/default/classes/IBMSpeechToTextV1Test.cls
- force-app/main/default/classes/IBMVisualRecognitionV3Models.cls
- force-app/main/default/classes/IBMVisualRecognitionV3Test.cls
- force-app/main/default/classes/IBMWatsonService.cls
This PR really just updates naming for variables that use reserved words to be camelCased, which follows the naming convention better. The larger changes for the pre-release like full regeneration, new authentication formats, and the big naming change were done in these earlier PRs:
- https://github.com/watson-developer-cloud/salesforce-sdk/pull/193
- https://github.com/watson-developer-cloud/salesforce-sdk/pull/195
> Final changes for 5.0.0 pre-release

- force-app/main/default/classes/IBMWatsonClient.cls
- force-app/main/default/classes/IBMWatsonMultipartBody.cls
- force-app/main/default/classes/IBMWatsonServiceTest.cls
This PR fixes an issue when trying to use the `threshold` parameter in the `classify()` endpoint in Visual Recognition. The service would previously respond with an error complaining about the supplied `threshold` value.
After some debugging with someone from the Visual Recognition team, we found that the value was being sent as a string with a trailing space, which was the issue. In looking through the code to build up the form data, I saw a lot of logic adding trailing spaces to play well with base 64 encoding, which was previously being done for every piece of the multipart form body. [This class](https://github.com/MetaMind/apex-utils/blob/master/HttpFormBuilder.apex) seems to be the initial inspiration for the logic. Since Apex doesn't really have support for this built in, I saw …
> Remove base64 encoding when building multipart/form-data

- .bumpversion.cfg
- force-app/main/default/classes/IBMPersonalityInsightsV3Test.cls
- force-app/main/default/classes/IBMVisualRecognitionV3Test.cls
- force-app/main/default/classes/IBMWatsonDynamicResponseModelTest.cls
- force-app/main/default/classes/IBMWatsonDynamicResponseModelTest.cls-meta.xml
- force-app/main/default/classes/IBMWatsonIAMToken.cls
- force-app/main/default/classes/IBMWatsonICP4DTokenResponse.cls
- force-app/main/default/classes/IBMWatsonICP4DTokenTest.cls
- force-app/main/default/classes/IBMWatsonICP4DTokenTest.cls-meta.xml
- force-app/main/default/classes/IBMWatsonNoauthAuthenticatorTest.cls
- force-app/main/default/classes/IBMWatsonNoauthAuthenticatorTest.cls-meta.xml
- force-app/main/default/classes/IBMWatsonResponseModelTest.cls
- force-app/main/default/classes/IBMWatsonResponseModelTest.cls-meta.xml
- force-app/main/default/classes/IBMWatsonService.cls
- force-app/main/default/classes/IBMWatsonServiceTest.cls
Fixes https://github.com/watson-developer-cloud/salesforce-sdk/issues/201
The last patch release I did got the coverage of the full SDK over 75%, which I mistakenly thought was enough to push to production. Apparently this was wrong, so this PR bumps up the test coverage numbers of every class to this point.
> Get test coverage of all classes to at least 75%

- force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Models.cls
This PR adds back the `model` parameter in `CategoriesOptions`, which was mistakenly removed. This parameter _is_ deprecated though, as it's no longer supported in the service.
> Add mistakenly-removed parameter in NLU
