watson-developer-cloud/salesforce-sdk

force-app/main/test/IBMConversationV1FTests.cls, force-app/main/test/IBMDiscoveryV1FTests.cls
Classes and functions with the @isTest annotation are not counted against the 3mb Apex code limit
=> Mark the integration tests as being tests

force-app/main/default/classes/IBMWatsonService.cls
Allow override of the authentication mechanisms by the different services, adding token to Visual Recognition service.
=> allow authentication method override and token key

force-app/main/default/classes/IBMVisualRecognitionV3.cls, force-app/main/default/classes/IBMWatsonService.cls
override authentication mechanism for this service using the core fix
=> adding token based override to service authentication

.travis.yml, config/remoteSiteEndpoint/WatsonTextToSpeech.remoteSite, config/remoteSiteEndpoint/remoteSiteSettings/WatsonTextToSpeech.remoteSite, force-app/main/default/classes/IBMTextToSpeechV1.cls, force-app/main/default/classes/IBMTextToSpeechV1.cls-meta.xml, force-app/main/default/classes/IBMTextToSpeechV1Models.cls, force-app/main/default/classes/IBMTextToSpeechV1Models.cls-meta.xml, force-app/main/default/classes/IBMTextToSpeechV1Test.cls, force-app/main/default/classes/IBMTextToSpeechV1Test.cls-meta.xml, force-app/main/default/classes/IBMWatsonMockResponses.cls, force-app/main/test/IBMTextToSpeechV1FTest.cls, force-app/main/test/IBMTextToSpeechV1FTest.cls-meta.xml
Functional and unit tests. Merge will happen once tests are complete
=> Text to speech

.travis.yml, README.md, force-app/main/test/IBMSpeechToTextV1FTest.cls
This PR adds in documentation changes to reflect all services being out and explains the suggested workaround for the lack of WebSocket support.
It also adds the running of functional tests for Speech to Text to Travis and fixes some formatting issues with tabs.
=> Final fixes before release

force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Test.cls
=> Fix url in NLU unit test class

config/SFDXService/sfdx-deploy-config.json, install/sfdx-deploy-service.sh
Deploys selected services to scratch orgs, on its current version the script assumes the scratch org was already created.
The script is located inside the `install` folder and the configuration file is located on the `config/SFDXService` folder.
Usage: /sfdx-deploy-service.sh -c -s discovery -u test-yqejio8nyef5@company.net
=> SFDX service deployment

force-app/main/default/classes/IBMDiscoveryV1.cls, force-app/main/default/classes/IBMDiscoveryV1Models.cls
Summary display changes - Added version date, commented id_serialized_name
=> summary changes

force-app/main/default/classes/IBMVisualRecognitionV3.cls, force-app/main/default/classes/IBMVisualRecognitionV3Models.cls, force-app/main/default/classes/IBMVisualRecognitionV3Test.cls, force-app/main/test/IBMVisualRecognitionV3FTest.cls
This PR adds the newest Visual Recognition code as of the week of 03/05/18.
=> [Visual Recognition] Add newest generated code and update tests

force-app/main/default/classes/IBMToneAnalyzerV3.cls, force-app/main/default/classes/IBMToneAnalyzerV3Models.cls, force-app/main/default/classes/IBMToneAnalyzerV3Test.cls, force-app/main/test/IBMToneAnalyzerV3FTest.cls
This PR adds the newest Tone Analyzer code as of the week of 03/05/18.
=> [Tone Analyzer] Add newest generated code

force-app/main/default/classes/IBMTextToSpeechV1.cls, force-app/main/default/classes/IBMTextToSpeechV1Models.cls, force-app/main/default/classes/IBMTextToSpeechV1Test.cls
This PR adds the newest Text to Speech code as of the week of 03/05/18.
=> [Text to Speech] Add newest generated code and update tests

force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMSpeechToTextV1Test.cls
This PR adds the newest Speech to Text code as of the week of 03/05/18.
=> [Speech to Text] Add newest generated code and update tests

force-app/main/default/classes/IBMConversationV1.cls, force-app/main/default/classes/IBMConversationV1Models.cls, force-app/main/default/classes/IBMConversationV1Test.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls, force-app/main/test/IBMConversationV1FTests.cls
This PR adds the newest Conversation code as of the week of 03/05/18.
=> [Conversation] Add newest generated code and update tests

force-app/main/default/classes/IBMDiscoveryV1.cls, force-app/main/default/classes/IBMDiscoveryV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1Test.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls, force-app/main/test/IBMDiscoveryV1FTests.cls
This PR adds the newest Discovery code as of the week of 03/05/18.
=> [Discovery] Add newest generated code and update tests

force-app/main/default/classes/IBMNaturalLanguageClassifierV1.cls, force-app/main/default/classes/IBMNaturalLanguageClassifierV1Models.cls
This PR adds the newest Natural Language Classifier code as of the week of 03/05/18.
=> [Natural Language Classifier] Add newest generated code and update tests

force-app/main/default/classes/IBMLanguageTranslatorV2.cls, force-app/main/default/classes/IBMLanguageTranslatorV2Models.cls, force-app/main/test/IBMLanguageTranslatorV2FTest.cls
This PR adds the newest Language Translator code as of the week of 03/05/18.
=> [Language Translator] Add newest generated code and update tests

.travis.yml, force-app/main/default/classes/IBMDiscoveryV1.cls, force-app/main/default/classes/IBMDiscoveryV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1Test.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls
This PR adds the newest generated code for the Discovery service as of 4/25/18 and updates tests accordingly.
This PR also fixes the Travis issue causing the other PRs to fail.
=> [Discovery] Add newest generated code

force-app/main/default/classes/IBMConversationV1.cls, force-app/main/default/classes/IBMConversationV1Models.cls, force-app/main/default/classes/IBMConversationV1Test.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls
This PR adds the newest generated code for the Conversation service as of 4/25/18 and updates tests accordingly.
=>  [Conversation] Add newest generated code

force-app/main/default/classes/IBMLanguageTranslatorV2.cls, force-app/main/default/classes/IBMLanguageTranslatorV2Models.cls
This PR adds the newest generated code for the Language Translator service as of 4/25/18 and updates tests accordingly.
No functional changes were made in this PR.
=> [Language Translator] Add newest generated code

force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMSpeechToTextV1Test.cls
This PR adds the newest generated code for the Speech to Text service as of 4/25/18 and updates tests accordingly.
=>  [Speech to Text] Add newest generated code

force-app/main/default/classes/IBMVisualRecognitionV3Models.cls, force-app/main/default/classes/IBMVisualRecognitionV3Test.cls
This PR adds the newest generated code for the Visual Recognition service as of 4/25/18 and updates tests accordingly.
=> [Visual Recognition] Add newest generated code

force-app/main/default/classes/IBMAssistantV1.cls, force-app/main/default/classes/IBMAssistantV1Models.cls, force-app/main/default/classes/IBMAssistantV1Test.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls
This PR adds the newest generated code for the Assistant service as of 4/25/18 and updates tests accordingly.
=> [Assistant] Add newest generated code

force-app/main/default/classes/IBMAssistantV1.cls, force-app/main/default/classes/IBMAssistantV1Models.cls, force-app/main/default/classes/IBMAssistantV1Test.cls
=> Add generated code for Assistant

force-app/main/default/classes/IBMConversationV1.cls, force-app/main/default/classes/IBMConversationV1Models.cls, force-app/main/default/classes/IBMConversationV1Test.cls
=> Add generated code for Conversation

force-app/main/default/classes/IBMDiscoveryV1.cls, force-app/main/default/classes/IBMDiscoveryV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1Test.cls
=> Add generated code for Discovery

force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1.cls
=> Add generated code for NLU

force-app/main/default/classes/IBMPersonalityInsightsV3.cls, force-app/main/default/classes/IBMPersonalityInsightsV3Models.cls
=> Add generated code for Personality Insights

force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls
=> Add generated code for Speech to Text

force-app/main/default/classes/IBMTextToSpeechV1.cls
=> Add generated code for Text to Speech

.bumpversion.cfg, .gitignore, force-app/main/default/classes/IBMAssistantV1.cls, force-app/main/default/classes/IBMAssistantV1Models.cls, force-app/main/default/classes/IBMConversationV1.cls, force-app/main/default/classes/IBMConversationV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1.cls, force-app/main/default/classes/IBMDiscoveryV1Models.cls, force-app/main/default/classes/IBMLanguageTranslatorV2.cls, force-app/main/default/classes/IBMLanguageTranslatorV3.cls, force-app/main/default/classes/IBMLanguageTranslatorV3.cls-meta.xml, force-app/main/default/classes/IBMLanguageTranslatorV3Models.cls, force-app/main/default/classes/IBMLanguageTranslatorV3Models.cls-meta.xml, force-app/main/default/classes/IBMLanguageTranslatorV3Test.cls, force-app/main/default/classes/IBMLanguageTranslatorV3Test.cls-meta.xml, force-app/main/default/classes/IBMNaturalLanguageClassifierV1.cls, force-app/main/default/classes/IBMNaturalLanguageClassifierV1Models.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Models.cls, force-app/main/default/classes/IBMPersonalityInsightsV3.cls, force-app/main/default/classes/IBMPersonalityInsightsV3Models.cls, force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMTextToSpeechV1.cls, force-app/main/default/classes/IBMTextToSpeechV1Models.cls, force-app/main/default/classes/IBMToneAnalyzerV3.cls, force-app/main/default/classes/IBMToneAnalyzerV3Models.cls, force-app/main/default/classes/IBMVisualRecognitionV3.cls, force-app/main/default/classes/IBMVisualRecognitionV3Models.cls, force-app/main/default/classes/IBMWatsonService.cls
This PR is the result of the newest codegen cycle. The main change is the addition of LTv3, with most of the other files only having comments changed.
Those codegen updates use the following commits:
- API Definition: `a3d247f2d250edf5b9743a41afcfebda52f66cf4`
- Codegen: `1b4341039c46d6794f65a12932698cb7aeb1c236`
=> Add codegen changes

README.md, force-app/main/default/classes/IBMLanguageTranslatorV2.cls
This PR adds a deprecation notice both in the Language Translator v2 class and in the README.
=> Add deprecation notice for Language Translator v2

force-app/main/default/classes/IBMWatsonMultipartBody.cls, force-app/main/default/classes/IBMWatsonService.cls
This PR fixes two issues: one related to file uploading errors and the other related to a namespacing error when the SDK is deployed.
=> Release v2.3.2

README.md
This pull request adds onboarding tracking and revises readme to be consistent across the SDKs.
=> Onboarding tracking

force-app/main/default/classes/IBMAssistantV1Models.cls, force-app/main/default/classes/IBMConversationV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1.cls, force-app/main/default/classes/IBMDiscoveryV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1Test.cls, force-app/main/default/classes/IBMLanguageTranslatorV2.cls, force-app/main/default/classes/IBMPersonalityInsightsV3Models.cls, force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMToneAnalyzerV3Models.cls, force-app/main/default/classes/IBMVisualRecognitionV3.cls, force-app/main/default/classes/IBMVisualRecognitionV3Models.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls, force-app/main/test/IBMDiscoveryV1FTests.cls
This PR includes the updates from the latest code regeneration, using the following commits:
- Codegen: `e382f8c2514ba6bddb96f9794ac2f99f9ea5d427`
- API definition: `109a00d6dd5ab0bca1f89ab23b3e637d8fdca1ff`
The main changes are the addition of `Credentials` methods in Discovery, as well as some other parameter additions. The rest is just comment/documentation changes.
=> Codegen updates

README.md, force-app/main/default/classes/IBMAssistantV1Models.cls, force-app/main/default/classes/IBMConversationV1.cls, force-app/main/default/classes/IBMConversationV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1.cls, force-app/main/default/classes/IBMDiscoveryV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1Test.cls, force-app/main/default/classes/IBMNaturalLanguageClassifierV1Models.cls, force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMVisualRecognitionV3Models.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls, force-app/main/test/IBMDiscoveryV1FTests.cls
This PR contains changes for the v2.6.0 release. It uses the following commits:
- Codegen: `2590ceea86dc97127f9afa67c79a3c321dd68e5c`
- API definition: `053ee5d76d6bdf82c0cb146a98e459dba2e5b0cd`
Full details will be in the changelog upon release.
=> Release v2.6.0

force-app/main/default/classes/IBMAssistantV1Models.cls, force-app/main/default/classes/IBMAssistantV1Test.cls, force-app/main/default/classes/IBMConversationV1Models.cls, force-app/main/default/classes/IBMConversationV1Test.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Models.cls, force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls
This PR contains changes for the v2.8.0 release. This was generated using the following commits:
- Codegen: `f0f4bd2be4a8d0e52a97f6df0d74f2f864d60499`
- API definition: `353dcba8489dab421e9066b1748a566b0e8ed263`
Full details will be in the changelog upon release.
=> Release v2.8.0

force-app/main/default/classes/IBMDiscoveryV1.cls, force-app/main/default/classes/IBMDiscoveryV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1Test.cls, force-app/main/default/classes/IBMLanguageTranslatorV3Models.cls, force-app/main/default/classes/IBMNaturalLanguageClassifierV1.cls, force-app/main/default/classes/IBMNaturalLanguageClassifierV1Models.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Models.cls, force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls, force-app/main/test/IBMDiscoveryV1FTests.cls
This PR contains changes for release v3.1.0 of the Salesforce SDK using the following commits:
- Codegen: `17986b7921b9440e72bfb68d3febeb0cda12b7bd`
- API definition: `69548d73e9f9b65a549772bdc949087959f9a35e`
The main change in this release is the addition of 3 new methods in the Discovery service: `createTokenizationDictionary()`, `getTokenizationDictionaryStatus()`, and `deleteTokenizationDictionary()`.
Full details will be in the changelog upon release.
=> Release v3.1.0

config/SFDXService/sfdx-deploy-config.json, force-app/main/default/classes/IBMAssistantV1.cls, force-app/main/default/classes/IBMAssistantV1Models.cls, force-app/main/default/classes/IBMAssistantV1Test.cls, force-app/main/default/classes/IBMCompareComplyV1.cls, force-app/main/default/classes/IBMCompareComplyV1.cls-meta.xml, force-app/main/default/classes/IBMCompareComplyV1Models.cls, force-app/main/default/classes/IBMCompareComplyV1Models.cls-meta.xml, force-app/main/default/classes/IBMCompareComplyV1Test.cls, force-app/main/default/classes/IBMCompareComplyV1Test.cls-meta.xml, force-app/main/default/classes/IBMDiscoveryV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1Test.cls, force-app/main/default/classes/IBMLanguageTranslatorV3Models.cls, force-app/main/default/classes/IBMNaturalLanguageClassifierV1Models.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Models.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Test.cls, force-app/main/default/classes/IBMPersonalityInsightsV3.cls, force-app/main/default/classes/IBMPersonalityInsightsV3Models.cls, force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMTextToSpeechV1.cls, force-app/main/default/classes/IBMTextToSpeechV1Models.cls, force-app/main/default/classes/IBMToneAnalyzerV3.cls, force-app/main/default/classes/IBMToneAnalyzerV3Models.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls, force-app/main/test/IBMCompareComplyV1FTests.cls, force-app/main/test/IBMCompareComplyV1FTests.cls-meta.xml, install/test-in-scratch-org.sh
This PR contains changes for release v3.2.0 of the Salesforce SDK using the following commits:
- Codegen: `373a129b5ba34270f943d1773b881b7473915ac4`
- API definition: `28d3855fc2ffb35704d13e467d555dd1e6576104`
The main change in the addition of the ✨ **Compare and Comply service**✨. Other changes will be in the generated changelog.
=> Release v3.2.0

.pre-commit-config.yaml, .secrets.baseline, force-app/main/default/classes/IBMAssistantV2Models.cls, force-app/main/default/classes/IBMAssistantV2Test.cls, force-app/main/default/classes/IBMDiscoveryV1.cls, force-app/main/default/classes/IBMDiscoveryV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1Test.cls, force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMSpeechToTextV1Test.cls, force-app/main/default/classes/IBMVisualRecognitionV3.cls, force-app/main/default/classes/IBMVisualRecognitionV3Models.cls, force-app/main/default/classes/IBMVisualRecognitionV3Test.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls, force-app/main/test/IBMDiscoveryV1FTests.cls
This PR contains changes for release v3.3.0 of the Salesforce SDK using the following commits:
- Codegen: `fd2b26eaa85deb4260f5e18df2d963e2872adb80`
- API definition: `dd3a357da256edd821cb99cfc06d71025384598f`
The main changes in this release are new endpoints for Discovery and Speech to Text. Full details will be in the changelog upon release.
=> Release 3.3.0

.secrets.baseline, force-app/main/default/classes/IBMAssistantV1Models.cls, force-app/main/default/classes/IBMCompareComplyV1.cls, force-app/main/default/classes/IBMCompareComplyV1Models.cls, force-app/main/default/classes/IBMCompareComplyV1Test.cls, force-app/main/default/classes/IBMDiscoveryV1.cls, force-app/main/default/classes/IBMDiscoveryV1Models.cls, force-app/main/default/classes/IBMDiscoveryV1Test.cls, force-app/main/default/classes/IBMNaturalLanguageClassifierV1Models.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Models.cls, force-app/main/default/classes/IBMPersonalityInsightsV3Models.cls, force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMSpeechToTextV1Test.cls, force-app/main/default/classes/IBMVisualRecognitionV3Models.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls
This PR contains changes for release v3.4.0 of the Salesforce SDK using the following commits:
- Codegen: `a5d0b22673bd91f2802b06bf39e5b049501dcb18`
- API definition: `433f7fd45da5addb51abddb2616ec805aeb24da6`
Full details will be in the changelog upon release.
=> Release 3.4.0

force-app/main/default/classes/IBMWatsonMultipartBody.cls, force-app/main/default/classes/IBMWatsonResponse.cls
This PR contains two changes meant to be the final core changes before the upcoming release. These changes are:
- Refactoring the error parsing logic to align with the other Watson SDKs
- Defaulting to a filename of "filename" when one isn't provided to satisfy some service requirements
=> Final core changes

README.md, config/remoteSiteEndpoint/WatsonIAM.remoteSite, config/remoteSiteEndpoint/remoteSiteSettings/WatsonIAM.remoteSite, examples/assistant/README.md, examples/discovery/README.md, force-app/main/default/classes/IBMAssistantV2Models.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Models.cls, force-app/main/default/classes/IBMWatsonHttpHeaders.cls, force-app/main/default/classes/IBMWatsonIAMTokenManager.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls
This pull request refactors bluemix to cloud.ibm with the exception of example files and links to apps running in bluemix and one test that is using the api-explorer.
=> Refactor bluemix to cloud.ibm

examples/assistant/README.md
Seems like class names were modified and hence example snippet needs to b updated.
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here.
Thanks for contributing!
=> Proposing the changes w.r.t issue #185

.bumpversion.cfg, force-app/main/default/classes/IBMAssistantV1.cls, force-app/main/default/classes/IBMAssistantV2Models.cls, force-app/main/default/classes/IBMCompareComplyV1.cls, force-app/main/default/classes/IBMCompareComplyV1Models.cls, force-app/main/default/classes/IBMCompareComplyV1Test.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Models.cls, force-app/main/default/classes/IBMNaturalLanguageUnderstandingV1Test.cls, force-app/main/default/classes/IBMSpeechToTextV1.cls, force-app/main/default/classes/IBMSpeechToTextV1Models.cls, force-app/main/default/classes/IBMSpeechToTextV1Test.cls, force-app/main/default/classes/IBMWatsonMockResponses.cls
This PR contains changes for the 4.3.0 release of the SDK. The commits used for generation are as follows:
```
Generator
commit: ccf6b234675d0ff25d19fbafe18976dc21ad8462 from the apex-maint branch
API definition
tag: sdk-2019-07-22
```
Full details about changes will be in the generated changelog upon release.
=> Release 4.3.0
